### ISSUE TITLE
Actuadores

### ISSUE THREAD

**Issue by OrazioGatto** [USB-EC3081-III-2019/EC3081-G01#2]
Profesor, si quiero simular un aspersor para el control de riego, que actuado deberia de poner a representar ese aspersor ? un motor ?

**Comment by OrazioGatto** [comment]
Otra pregunta, el sensor de humedad de sustrado usted lo tiene ? por que en el prof. Villegas me dijo que no hay en el lab

**Comment by ncertad** [comment]
El movimiento de los aspersores reales no proviene de un motor, es el propio  flujo del agua el que hace que el aspersor gire. En nuestro caso el aspersor se simula con una electroválvula. El sensor de humedad es _homemade_
